"use client";

import { useState } from "react";
import { Taxonomy } from "@/lib/types";

interface GenerateViewProps {
  onComplete: (taxonomy: Taxonomy) => void;
}

export default function GenerateView({ onComplete }: GenerateViewProps) {
  const [apiKey, setApiKey] = useState("");
  const [status, setStatus] = useState<"idle" | "generating" | "error">("idle");
  const [error, setError] = useState("");
  const [progress, setProgress] = useState("");
  const [charCount, setCharCount] = useState(0);

  const handleGenerate = async () => {
    if (!apiKey.trim()) {
      setError("Please enter your Claude API key.");
      return;
    }
    setStatus("generating");
    setError("");
    setProgress("Connecting to Claude...");
    setCharCount(0);

    try {
      const res = await fetch("/api/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ apiKey: apiKey.trim() }),
      });

      if (!res.ok || !res.body) {
        throw new Error(`Request failed: ${res.status}`);
      }

      const reader = res.body.getReader();
      const decoder = new TextDecoder();
      let raw = "";

      setProgress("Generating taxonomy (this takes 2-4 minutes)...");

      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        const chunk = decoder.decode(value, { stream: true });
        raw += chunk;
        setCharCount(raw.length);

        if (raw.includes("__ERROR__:")) {
          const msg = raw.split("__ERROR__:")[1].trim();
          throw new Error(msg);
        }
      }

      setProgress("Parsing taxonomy...");

      // Extract JSON — find the outermost { ... }
      const start = raw.indexOf("{");
      const end = raw.lastIndexOf("}");
      if (start === -1 || end === -1) {
        throw new Error("No valid JSON found in response. Try generating again.");
      }
      const jsonStr = raw.slice(start, end + 1);
      const parsed = JSON.parse(jsonStr);

      if (!parsed.domains || !Array.isArray(parsed.domains)) {
        throw new Error("Unexpected JSON structure. Try generating again.");
      }

      const taxonomy: Taxonomy = {
        domains: parsed.domains,
        generatedAt: new Date().toISOString(),
      };

      // Cache in localStorage
      try {
        localStorage.setItem("omniscience_taxonomy", JSON.stringify(taxonomy));
      } catch {
        // localStorage might be full — non-fatal
      }

      onComplete(taxonomy);
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : "Unknown error";
      setError(message);
      setStatus("error");
    }
  };

  return (
    <div className="min-h-screen bg-gray-950 flex items-center justify-center p-6">
      <div className="w-full max-w-lg bg-gray-900 rounded-2xl p-8 border border-gray-800">
        <h1 className="text-3xl font-bold text-white mb-2">Omniscience</h1>
        <p className="text-gray-400 mb-8">
          A complete taxonomy of all human knowledge, generated by Claude AI.
          Enter your Anthropic API key to begin.
        </p>

        <div className="space-y-4">
          <div>
            <label className="block text-sm text-gray-400 mb-2">
              Anthropic API Key
            </label>
            <input
              type="password"
              value={apiKey}
              onChange={(e) => setApiKey(e.target.value)}
              placeholder="sk-ant-..."
              className="w-full bg-gray-800 text-gray-100 rounded-lg px-4 py-3 outline-none focus:ring-2 focus:ring-blue-500 placeholder-gray-600 font-mono text-sm"
              disabled={status === "generating"}
            />
          </div>

          {error && (
            <div className="bg-red-950 border border-red-800 rounded-lg px-4 py-3 text-red-300 text-sm">
              {error}
            </div>
          )}

          {status === "generating" && (
            <div className="bg-blue-950 border border-blue-800 rounded-lg px-4 py-3 space-y-2">
              <div className="flex items-center gap-3">
                <div className="w-4 h-4 border-2 border-blue-400 border-t-transparent rounded-full animate-spin flex-shrink-0" />
                <span className="text-blue-300 text-sm">{progress}</span>
              </div>
              {charCount > 0 && (
                <p className="text-blue-400 text-xs pl-7">
                  {charCount.toLocaleString()} characters received...
                </p>
              )}
            </div>
          )}

          <button
            onClick={handleGenerate}
            disabled={status === "generating"}
            className="w-full bg-blue-600 hover:bg-blue-500 disabled:bg-gray-700 disabled:cursor-not-allowed text-white font-semibold rounded-lg px-4 py-3 transition-colors"
          >
            {status === "generating" ? "Generating..." : "Generate Taxonomy"}
          </button>

          <p className="text-xs text-gray-600 text-center">
            Your API key is sent directly to Anthropic and never stored on any server.
            The generated taxonomy is cached in your browser&apos;s localStorage.
          </p>
        </div>
      </div>
    </div>
  );
}
